movie:
  video_file: "/home/mike/compile/slowmovie/input.mkv"

mqtt:
  addr: "192.168.1.135"
  topic: "slowmovie/frame"

screen_sizes:
  - name: "640x384"
    x: 640
    y: 384
  - name: "800x480"
    x: 800
    y: 480
